GET http://localhost:3000/travel

### GET /posts?title=json-server&author=typicode//

GET http://localhost:3000/travel?title=json-server&category=InterNational

### GET /posts?q=internet
GET http://localhost:3000/travel?q=paris

###
GET http://localhost:3000/travel/20